### ISSUE TITLE
Unappliable GUI

### ISSUE THREAD

**Issue by Vladg24YT** [PROGOI/WLC-Rolechat#4]
В текущей версии есть базовый пользовательский интерфейс, но он, честно говоря, хреновый. Главная проблема - динамическое изменение размера виджетов в случае изменения разрешения экрана. Ибо когда на экране 1920x1080 dp всё отображается корректно, то на экране в 640x480 dp ты видишь только центральную 1/5 экрана. 

Для получения размера экрана есть методы `getScreenWidth()` и `getScreenHeight()`, но функций для изменения размера самого виджета (`View`) нету. Что делать будем?

**Comment by ForesterGoGo** [comment]
сосатб кунс инд бегат
